// Mocks generated by Mockito 5.4.3 from annotations
// in veegil_bank/test/features/transactions/domain/use_cases/transfer_funds_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:veegil_bank/features/transactions/domain/entities/transfer_entity.dart'
    as _i2;
import 'package:veegil_bank/features/transactions/domain/repositories/transfer_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransferEntity_0 extends _i1.SmartFake
    implements _i2.TransferEntity {
  _FakeTransferEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferRepository extends _i1.Mock
    implements _i3.TransferRepository {
  @override
  _i4.Future<_i2.TransferEntity> transferFunds(int? amount) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferFunds,
          [amount],
        ),
        returnValue: _i4.Future<_i2.TransferEntity>.value(_FakeTransferEntity_0(
          this,
          Invocation.method(
            #transferFunds,
            [amount],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TransferEntity>.value(_FakeTransferEntity_0(
          this,
          Invocation.method(
            #transferFunds,
            [amount],
          ),
        )),
      ) as _i4.Future<_i2.TransferEntity>);
}
