// Mocks generated by Mockito 5.4.3 from annotations
// in veegil_bank/test/core/infastructure/platform/connectivity_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:veegil_bank/core/infastructure/platform/connectivity_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [InternetChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetChecker extends _i1.Mock implements _i2.InternetChecker {
  @override
  _i3.Future<bool> isInternetAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isInternetAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
